services:
  warp-proxy:
    image: "867251765/warp-docker-proxy:latest"
    container_name: warp-docker-proxy
    hostname: warp-docker-proxy
    ports:
      - "41080:1080"
    restart: unless-stopped    
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun      
    environment:
      - DEBIAN_FRONTEND=noninteractive
      # Set WARP_TOKEN if you want to use ZeroTrust
      # ep "com.cloudflare.warp://"
      - WARP_TOKEN=
      # set PROXY_USER and PROXY_PASSWORD if you want auth your proxy
      - PROXY_USER=
      - PROXY_PASSWORD=
      # set WARP_LICENSE if you have license with free (not ZeroTrust)
      - WARP_LICENSE=
    volumes:
      - ./data:/var/lib/cloudflare-warp
    healthcheck:
      test: ["CMD", "warp-cli", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
