[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:warp-svc]
command=/usr/bin/warp-svc
priority=100
autostart=true
autorestart=true
stdout_logfile=/logs/warp-svc.log
stderr_logfile=/logs/warp-svc.err.log

[program:warp-setup]
command=/usr/local/bin/warp-setup.sh
priority=200
autostart=true
autorestart=false
startsecs=0
stdout_logfile=/logs/warp-setup.log
stderr_logfile=/logs/warp-setup.err.log

[program:gost]
command=/usr/local/bin/gost-setup.sh
priority=300
autostart=true
autorestart=true
stdout_logfile=/logs/gost.log
stderr_logfile=/logs/gost.err.log

[program:clean-logs]
command=/usr/local/bin/clean-logs.sh
priority=400
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null
