name: Delete old SHA images
on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 00:00 执行
  workflow_dispatch: # 允许手动触发

jobs:
  delete-old-images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: warp-docker-proxy
          tag-match-regex: ^sha-.*$
          cut-off: 7 days ago UTC
          keep-at-least: 5
          token: ${{ secrets.GITHUB_TOKEN }}
          account-type: personal  # 账户信息: 个人